# Generated by Django 5.2.4 on 2025-07-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('pergunta', models.TextField()),
                ('peso_maximo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Escuderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('esta_ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurado', models.CharField(max_length=100)),
                ('data_votacao', models.DateTimeField(auto_now_add=True)),
                ('escuderia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escuderia')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='core.votacao')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.criterio')),
                ('voto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.voto')),
            ],
        ),
    ]
