# Generated by Django 5.2.4 on 2025-07-25 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacao',
            name='criterios',
            field=models.ManyToManyField(to='core.criterio', verbose_name='Critérios da Votação'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='escuderia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_escuderia', to='core.escuderia'),
        ),
    ]
